[build]
# Railpack bakal sadar ini bukan aplikasi SPA statis
[variables]
RAILPACK_NO_SPA = "1"
PORT = "3000"

[deploy]
# Perintah ini bakal hapus karakter 'kotor' (sed) baru jalankan script-nya
startCommand = "sed -i 's/\r$//' start.sh && bash start.sh"
